require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HumanoidsController do

  # This should return the minimal set of attributes required to create a valid
  # Humanoid. As you add validations to Humanoid, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HumanoidsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all humanoids as @humanoids" do
      humanoid = Humanoid.create! valid_attributes
      get :index, {}, valid_session
      assigns(:humanoids).should eq([humanoid])
    end
  end

  describe "GET show" do
    it "assigns the requested humanoid as @humanoid" do
      humanoid = Humanoid.create! valid_attributes
      get :show, {:id => humanoid.to_param}, valid_session
      assigns(:humanoid).should eq(humanoid)
    end
  end

  describe "GET new" do
    it "assigns a new humanoid as @humanoid" do
      get :new, {}, valid_session
      assigns(:humanoid).should be_a_new(Humanoid)
    end
  end

  describe "GET edit" do
    it "assigns the requested humanoid as @humanoid" do
      humanoid = Humanoid.create! valid_attributes
      get :edit, {:id => humanoid.to_param}, valid_session
      assigns(:humanoid).should eq(humanoid)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Humanoid" do
        expect {
          post :create, {:humanoid => valid_attributes}, valid_session
        }.to change(Humanoid, :count).by(1)
      end

      it "assigns a newly created humanoid as @humanoid" do
        post :create, {:humanoid => valid_attributes}, valid_session
        assigns(:humanoid).should be_a(Humanoid)
        assigns(:humanoid).should be_persisted
      end

      it "redirects to the created humanoid" do
        post :create, {:humanoid => valid_attributes}, valid_session
        response.should redirect_to(Humanoid.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved humanoid as @humanoid" do
        # Trigger the behavior that occurs when invalid params are submitted
        Humanoid.any_instance.stub(:save).and_return(false)
        post :create, {:humanoid => {  }}, valid_session
        assigns(:humanoid).should be_a_new(Humanoid)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Humanoid.any_instance.stub(:save).and_return(false)
        post :create, {:humanoid => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested humanoid" do
        humanoid = Humanoid.create! valid_attributes
        # Assuming there are no other humanoids in the database, this
        # specifies that the Humanoid created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Humanoid.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => humanoid.to_param, :humanoid => { "these" => "params" }}, valid_session
      end

      it "assigns the requested humanoid as @humanoid" do
        humanoid = Humanoid.create! valid_attributes
        put :update, {:id => humanoid.to_param, :humanoid => valid_attributes}, valid_session
        assigns(:humanoid).should eq(humanoid)
      end

      it "redirects to the humanoid" do
        humanoid = Humanoid.create! valid_attributes
        put :update, {:id => humanoid.to_param, :humanoid => valid_attributes}, valid_session
        response.should redirect_to(humanoid)
      end
    end

    describe "with invalid params" do
      it "assigns the humanoid as @humanoid" do
        humanoid = Humanoid.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Humanoid.any_instance.stub(:save).and_return(false)
        put :update, {:id => humanoid.to_param, :humanoid => {  }}, valid_session
        assigns(:humanoid).should eq(humanoid)
      end

      it "re-renders the 'edit' template" do
        humanoid = Humanoid.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Humanoid.any_instance.stub(:save).and_return(false)
        put :update, {:id => humanoid.to_param, :humanoid => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested humanoid" do
      humanoid = Humanoid.create! valid_attributes
      expect {
        delete :destroy, {:id => humanoid.to_param}, valid_session
      }.to change(Humanoid, :count).by(-1)
    end

    it "redirects to the humanoids list" do
      humanoid = Humanoid.create! valid_attributes
      delete :destroy, {:id => humanoid.to_param}, valid_session
      response.should redirect_to(humanoids_url)
    end
  end

end
